# Generated by Django 4.2.10 on 2024-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_appuser_is_staff_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='appuser',
            name='ethnicity',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Other', 'Other')], default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
    ]
