# Generated by Django 5.0.2 on 2024-04-20 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('type', models.CharField(default='N/A', max_length=100)),
                ('source', models.CharField(default='N/A', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('blood_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_tests.bloodtest')),
            ],
        ),
        migrations.CreateModel(
            name='gptRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(default='N/A', max_length=50)),
                ('high_low', models.CharField(default='N/A', max_length=10)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('blood_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_tests.bloodtest')),
            ],
        ),
    ]
