# Generated by Django 5.0.2 on 2024-04-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='source',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='type',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
