# Generated by Django 4.2.10 on 2024-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_tests', '0002_bloodtest_source_bloodtest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='id',
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
