# Generated by Django 4.2.10 on 2024-04-12 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blood_tests', '0003_remove_bloodtest_id_alter_bloodtest_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='test_date',
            field=models.DateField(),
        ),
    ]
