# Generated by Django 4.2.10 on 2024-04-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_tests', '0004_bloodtest_id_alter_bloodtest_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='num',
        ),
    ]
