# Generated by Django 4.2.10 on 2024-04-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_tests', '0005_remove_bloodtest_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='gptRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('blood_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_tests.bloodtest')),
            ],
        ),
    ]
