# Generated by Django 4.2.10 on 2024-04-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_tests', '0006_gptrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptrecommendation',
            name='high_low',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='gptrecommendation',
            name='marker',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
