# Generated by Django 5.0.2 on 2024-02-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(default='F'),
        ),
    ]
