# Generated by Django 4.2.10 on 2024-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('Chinese', 'Chinese')], default='Black', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='Male', max_length=1),
            preserve_default=False,
        ),
    ]
